# nixpacks.toml
[phases.setup]
cmds = [
  "cd backend && pip install -r requirements.txt"
]

[phases.install]
cmds = []

[start]
cmd = "cd backend && python app.py"
ports = [5000]

[phases.build]
cmds = []